name: Deploy to Pantheon Live

on:
  push:
    branches:
      - main

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Sync to Remote Repository
      uses: alleyinteractive/action-deploy-to-remote-repository@v1
      with:
        remote_repo: 'git@github.com:praveenr4901/piwigo.git'
        remote_branch: 'main'
        destination_directory: '/home/xminds/test'
        exclude_list: '.git,.github,.gitmodules,node_modules'
        pantheon: 'false' # Assuming this is not a Pantheon environment
        ssh-key: ${{ secrets.REMOTE_REPO_SSH_KEY }}
