on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest
    
    steps:
      - name: Install SSH keys
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Connect and Pull
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
